// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpUG5dxsKLolV55OtkbDrxVddS80qgUu0',
    appId: '1:733269034271:web:506a35650808a0e41b9c2a',
    messagingSenderId: '733269034271',
    projectId: 'averis-de30e',
    authDomain: 'averis-de30e.firebaseapp.com',
    storageBucket: 'averis-de30e.firebasestorage.app',
    measurementId: 'G-PGEGJ7PE30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNmFkD37guVj2nFoo_yaDrCav-iiCvC4s',
    appId: '1:733269034271:android:f253fa9e4ea75cae1b9c2a',
    messagingSenderId: '733269034271',
    projectId: 'averis-de30e',
    storageBucket: 'averis-de30e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRU3FlatHFJ0n3E3BZg_IdjaY35ZSD8k',
    appId: '1:733269034271:ios:d39ccde991fc1fa61b9c2a',
    messagingSenderId: '733269034271',
    projectId: 'averis-de30e',
    storageBucket: 'averis-de30e.firebasestorage.app',
    iosBundleId: 'com.example.averis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtRU3FlatHFJ0n3E3BZg_IdjaY35ZSD8k',
    appId: '1:733269034271:ios:d39ccde991fc1fa61b9c2a',
    messagingSenderId: '733269034271',
    projectId: 'averis-de30e',
    storageBucket: 'averis-de30e.firebasestorage.app',
    iosBundleId: 'com.example.averis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpUG5dxsKLolV55OtkbDrxVddS80qgUu0',
    appId: '1:733269034271:web:e65a72e90c0a89421b9c2a',
    messagingSenderId: '733269034271',
    projectId: 'averis-de30e',
    authDomain: 'averis-de30e.firebaseapp.com',
    storageBucket: 'averis-de30e.firebasestorage.app',
    measurementId: 'G-9TX1CSEVWG',
  );
}
